### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by huifenghc** [ElementAI/beyond-trivial-explanations#5]
hello

I got an error on command(python trainval.py -e random_search -sb ./logs/bte -d ./data -r 1)

my error:
Traceback (most recent call last):
  File "trainval.py", line 155, in <module>
    results_fname='results.ipynb')
  File "/hd12/anaconda3/envs/dive_3.6/lib/python3.6/site-packages/haven/haven_wizard.py", line 145, in run_wizard
    func(exp_dict=exp_dict, savedir=savedir, args=args)
  File "trainval.py", line 76, in trainval
    train_dict = model.train_on_loader(epoch, train_loader)
  File "/hd12/anaconda3/envs/dive_3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1178, in __getattr__
    type(self).__name__, name))
AttributeError: 'GradientAttack' object has no attribute 'train_on_loader'

and I also checked that the GradientAttack class does not have the train_on_loader attribute.

I am not sure what is the cause of the problem, looking forward to your help.

**Comment by prlz77** [comment]
Ah probably it should be `run_scripts.py` instead of `trainval.py`. Would you mind trying it?

**Comment by prlz77** [comment]
Although it should work anyways since the attacks are performed in the constructor (https://github.com/ServiceNow/beyond-trivial-explanations/blob/prepare_transfer/src/wrappers/gradient_attacks.py#L90) and the error you got is after the constructor has finished.

Off course, best is not getting any error at all.

**Comment by huifenghc** [comment]
you mean i should run run_scripts.py ?

**Comment by prlz77** [comment]
Yes

**Comment by huifenghc** [comment]
hello，

The issue has been resolved by running the  run_scripts file. So what is the difference between trainval.py file and run_scripts.py file?

 looking forward to your help.
